import os
os.environ["HF_HOME"] = "/raid/rsq813/hugging_face"

import config

MEDCPT_QUERY_ENCODER = "ncbi/MedCPT-Query-Encoder"
MEDCPT_ARTICLE_ENCODER = "ncbi/MedCPT-Article-Encoder"
MEDCPT_BATCH_SIZE = 64

BM25_TITLE_BOOST = 2
PYSERINI_INDEX_THREADS = 8
BM25_K1 = 0.9
BM25_B = 0.4

YAHOO_MIN_ANSWER_WORDS = 5
YAHOO_MIN_TOTAL_WORDS = 10

RRF_K = 60

RETRIEVER_TYPES = ["bm25", "tfidf", "medcpt", "hybrid"]

EXTENDED_CONDITIONS = {
    "A": {"retriever": "baseline", "corpus": "none",   "queries": "meqsum",  "user_type": "layperson",
          "label": "Baseline + Lay"},
    "B": {"retriever": "baseline", "corpus": "none",   "queries": "bioasq_taskb", "user_type": "expert",
          "label": "Baseline + Expert"},
    "C": {"retriever": "bm25",     "corpus": "bioasq", "queries": "meqsum",  "user_type": "layperson",
          "label": "BM25-BioASQ + Lay"},
    "D": {"retriever": "bm25",     "corpus": "bioasq", "queries": "bioasq_taskb", "user_type": "expert",
          "label": "BM25-BioASQ + Expert"},
    "E": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "meqsum",  "user_type": "layperson",
          "label": "BM25-Yahoo + Lay"},
    "F": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "bioasq_taskb", "user_type": "expert",
          "label": "BM25-Yahoo + Expert"},
    "G": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "meqsum",  "user_type": "layperson",
          "label": "TFIDF-BioASQ + Lay"},
    "H": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "bioasq_taskb", "user_type": "expert",
          "label": "TFIDF-BioASQ + Expert"},
    "I": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "meqsum",  "user_type": "layperson",
          "label": "TFIDF-Yahoo + Lay"},
    "J": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "bioasq_taskb", "user_type": "expert",
          "label": "TFIDF-Yahoo + Expert"},
    "K": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "meqsum",  "user_type": "layperson",
          "label": "MedCPT-BioASQ + Lay"},
    "L": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "bioasq_taskb", "user_type": "expert",
          "label": "MedCPT-BioASQ + Expert"},
    "M": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "meqsum",  "user_type": "layperson",
          "label": "MedCPT-Yahoo + Lay"},
    "N": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "bioasq_taskb", "user_type": "expert",
          "label": "MedCPT-Yahoo + Expert"},
    "O": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "meqsum",  "user_type": "layperson",
          "label": "Hybrid-BioASQ + Lay"},
    "P": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "bioasq_taskb", "user_type": "expert",
          "label": "Hybrid-BioASQ + Expert"},
    "Q": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "meqsum",  "user_type": "layperson",
          "label": "Hybrid-Yahoo + Lay"},
    "R": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "bioasq_taskb", "user_type": "expert",
          "label": "Hybrid-Yahoo + Expert"},
    "A1": {"retriever": "baseline", "corpus": "none",   "queries": "medredqa", "user_type": "layperson",
           "label": "Baseline + MedRedQA"},
    "B1": {"retriever": "baseline", "corpus": "none",   "queries": "medquad", "user_type": "expert",
           "label": "Baseline + MedQuAD"},
    "C1": {"retriever": "bm25",     "corpus": "bioasq", "queries": "medredqa", "user_type": "layperson",
           "label": "BM25-BioASQ + MedRedQA"},
    "D1": {"retriever": "bm25",     "corpus": "bioasq", "queries": "medquad", "user_type": "expert",
           "label": "BM25-BioASQ + MedQuAD"},
    "E1": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "medredqa", "user_type": "layperson",
           "label": "BM25-Yahoo + MedRedQA"},
    "F1": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "medquad", "user_type": "expert",
           "label": "BM25-Yahoo + MedQuAD"},
    "G1": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "medredqa", "user_type": "layperson",
           "label": "TFIDF-BioASQ + MedRedQA"},
    "H1": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "medquad", "user_type": "expert",
           "label": "TFIDF-BioASQ + MedQuAD"},
    "I1": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "medredqa", "user_type": "layperson",
           "label": "TFIDF-Yahoo + MedRedQA"},
    "J1": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "medquad", "user_type": "expert",
           "label": "TFIDF-Yahoo + MedQuAD"},
    "K1": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "medredqa", "user_type": "layperson",
           "label": "MedCPT-BioASQ + MedRedQA"},
    "L1": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "medquad", "user_type": "expert",
           "label": "MedCPT-BioASQ + MedQuAD"},
    "M1": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "medredqa", "user_type": "layperson",
           "label": "MedCPT-Yahoo + MedRedQA"},
    "N1": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "medquad", "user_type": "expert",
           "label": "MedCPT-Yahoo + MedQuAD"},
    "O1": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "medredqa", "user_type": "layperson",
           "label": "Hybrid-BioASQ + MedRedQA"},
    "P1": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "medquad", "user_type": "expert",
           "label": "Hybrid-BioASQ + MedQuAD"},
    "Q1": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "medredqa", "user_type": "layperson",
           "label": "Hybrid-Yahoo + MedRedQA"},
    "R1": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "medquad", "user_type": "expert",
           "label": "Hybrid-Yahoo + MedQuAD"},
    "A2": {"retriever": "baseline", "corpus": "none",   "queries": "medicationqa", "user_type": "layperson",
           "label": "Baseline + MedicationQA"},
    "B2": {"retriever": "baseline", "corpus": "none",   "queries": "medqa", "user_type": "expert",
           "label": "Baseline + MedQA"},
    "C2": {"retriever": "bm25",     "corpus": "bioasq", "queries": "medicationqa", "user_type": "layperson",
           "label": "BM25-BioASQ + MedicationQA"},
    "D2": {"retriever": "bm25",     "corpus": "bioasq", "queries": "medqa", "user_type": "expert",
           "label": "BM25-BioASQ + MedQA"},
    "E2": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "medicationqa", "user_type": "layperson",
           "label": "BM25-Yahoo + MedicationQA"},
    "F2": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "medqa", "user_type": "expert",
           "label": "BM25-Yahoo + MedQA"},
    "G2": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "medicationqa", "user_type": "layperson",
           "label": "TFIDF-BioASQ + MedicationQA"},
    "H2": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "medqa", "user_type": "expert",
           "label": "TFIDF-BioASQ + MedQA"},
    "I2": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "medicationqa", "user_type": "layperson",
           "label": "TFIDF-Yahoo + MedicationQA"},
    "J2": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "medqa", "user_type": "expert",
           "label": "TFIDF-Yahoo + MedQA"},
    "K2": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "medicationqa", "user_type": "layperson",
           "label": "MedCPT-BioASQ + MedicationQA"},
    "L2": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "medqa", "user_type": "expert",
           "label": "MedCPT-BioASQ + MedQA"},
    "M2": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "medicationqa", "user_type": "layperson",
           "label": "MedCPT-Yahoo + MedicationQA"},
    "N2": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "medqa", "user_type": "expert",
           "label": "MedCPT-Yahoo + MedQA"},
    "O2": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "medicationqa", "user_type": "layperson",
           "label": "Hybrid-BioASQ + MedicationQA"},
    "P2": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "medqa", "user_type": "expert",
           "label": "Hybrid-BioASQ + MedQA"},
    "Q2": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "medicationqa", "user_type": "layperson",
           "label": "Hybrid-Yahoo + MedicationQA"},
    "R2": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "medqa", "user_type": "expert",
           "label": "Hybrid-Yahoo + MedQA"},
    "A3": {"retriever": "baseline", "corpus": "none",   "queries": "mashqa", "user_type": "layperson",
           "label": "Baseline + MASH-QA"},
    "B3": {"retriever": "baseline", "corpus": "none",   "queries": "medmcqa", "user_type": "expert",
           "label": "Baseline + MedMCQA"},
    "C3": {"retriever": "bm25",     "corpus": "bioasq", "queries": "mashqa", "user_type": "layperson",
           "label": "BM25-BioASQ + MASH-QA"},
    "D3": {"retriever": "bm25",     "corpus": "bioasq", "queries": "medmcqa", "user_type": "expert",
           "label": "BM25-BioASQ + MedMCQA"},
    "E3": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "mashqa", "user_type": "layperson",
           "label": "BM25-Yahoo + MASH-QA"},
    "F3": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "medmcqa", "user_type": "expert",
           "label": "BM25-Yahoo + MedMCQA"},
    "G3": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "mashqa", "user_type": "layperson",
           "label": "TFIDF-BioASQ + MASH-QA"},
    "H3": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "medmcqa", "user_type": "expert",
           "label": "TFIDF-BioASQ + MedMCQA"},
    "I3": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "mashqa", "user_type": "layperson",
           "label": "TFIDF-Yahoo + MASH-QA"},
    "J3": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "medmcqa", "user_type": "expert",
           "label": "TFIDF-Yahoo + MedMCQA"},
    "K3": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "mashqa", "user_type": "layperson",
           "label": "MedCPT-BioASQ + MASH-QA"},
    "L3": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "medmcqa", "user_type": "expert",
           "label": "MedCPT-BioASQ + MedMCQA"},
    "M3": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "mashqa", "user_type": "layperson",
           "label": "MedCPT-Yahoo + MASH-QA"},
    "N3": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "medmcqa", "user_type": "expert",
           "label": "MedCPT-Yahoo + MedMCQA"},
    "O3": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "mashqa", "user_type": "layperson",
           "label": "Hybrid-BioASQ + MASH-QA"},
    "P3": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "medmcqa", "user_type": "expert",
           "label": "Hybrid-BioASQ + MedMCQA"},
    "Q3": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "mashqa", "user_type": "layperson",
           "label": "Hybrid-Yahoo + MASH-QA"},
    "R3": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "medmcqa", "user_type": "expert",
           "label": "Hybrid-Yahoo + MedMCQA"},
    "A4": {"retriever": "baseline", "corpus": "none",   "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "Baseline + ChatDoctor-iCliniq"},
    "B4": {"retriever": "baseline", "corpus": "none",   "queries": "mmlu_medical", "user_type": "expert",
           "label": "Baseline + MMLU Medical"},
    "C4": {"retriever": "bm25",     "corpus": "bioasq", "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "BM25-BioASQ + ChatDoctor-iCliniq"},
    "D4": {"retriever": "bm25",     "corpus": "bioasq", "queries": "mmlu_medical", "user_type": "expert",
           "label": "BM25-BioASQ + MMLU Medical"},
    "E4": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "BM25-Yahoo + ChatDoctor-iCliniq"},
    "F4": {"retriever": "bm25",     "corpus": "yahoo",  "queries": "mmlu_medical", "user_type": "expert",
           "label": "BM25-Yahoo + MMLU Medical"},
    "G4": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "TFIDF-BioASQ + ChatDoctor-iCliniq"},
    "H4": {"retriever": "tfidf",    "corpus": "bioasq", "queries": "mmlu_medical", "user_type": "expert",
           "label": "TFIDF-BioASQ + MMLU Medical"},
    "I4": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "TFIDF-Yahoo + ChatDoctor-iCliniq"},
    "J4": {"retriever": "tfidf",    "corpus": "yahoo",  "queries": "mmlu_medical", "user_type": "expert",
           "label": "TFIDF-Yahoo + MMLU Medical"},
    "K4": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "MedCPT-BioASQ + ChatDoctor-iCliniq"},
    "L4": {"retriever": "medcpt",   "corpus": "bioasq", "queries": "mmlu_medical", "user_type": "expert",
           "label": "MedCPT-BioASQ + MMLU Medical"},
    "M4": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "MedCPT-Yahoo + ChatDoctor-iCliniq"},
    "N4": {"retriever": "medcpt",   "corpus": "yahoo",  "queries": "mmlu_medical", "user_type": "expert",
           "label": "MedCPT-Yahoo + MMLU Medical"},
    "O4": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "Hybrid-BioASQ + ChatDoctor-iCliniq"},
    "P4": {"retriever": "hybrid",   "corpus": "bioasq", "queries": "mmlu_medical", "user_type": "expert",
           "label": "Hybrid-BioASQ + MMLU Medical"},
    "Q4": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "chatdoctor_icliniq", "user_type": "layperson",
           "label": "Hybrid-Yahoo + ChatDoctor-iCliniq"},
    "R4": {"retriever": "hybrid",   "corpus": "yahoo",  "queries": "mmlu_medical", "user_type": "expert",
           "label": "Hybrid-Yahoo + MMLU Medical"},
}

NEW_RETRIEVAL_CONDITIONS = {
    "A11": {"retriever": "baseline", "corpus": "none", "queries": "meqsum", "user_type": "layperson",
            "label": "Baseline + Lay"},
    "B11": {"retriever": "baseline", "corpus": "none", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "Baseline + Expert"},
    "C11": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "meqsum", "user_type": "layperson",
            "label": "BM25-MedicalTextbooks + Lay"},
    "D11": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "BM25-MedicalTextbooks + Expert"},
    "E11": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "meqsum", "user_type": "layperson",
            "label": "BM25-HealthCareMagic + Lay"},
    "F11": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "BM25-HealthCareMagic + Expert"},
    "G11": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "meqsum", "user_type": "layperson",
            "label": "TFIDF-MedicalTextbooks + Lay"},
    "H11": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "TFIDF-MedicalTextbooks + Expert"},
    "I11": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "meqsum", "user_type": "layperson",
            "label": "TFIDF-HealthCareMagic + Lay"},
    "J11": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "TFIDF-HealthCareMagic + Expert"},
    "K11": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "meqsum", "user_type": "layperson",
            "label": "MedCPT-MedicalTextbooks + Lay"},
    "L11": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "MedCPT-MedicalTextbooks + Expert"},
    "M11": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "meqsum", "user_type": "layperson",
            "label": "MedCPT-HealthCareMagic + Lay"},
    "N11": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "MedCPT-HealthCareMagic + Expert"},
    "O11": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "meqsum", "user_type": "layperson",
            "label": "Hybrid-MedicalTextbooks + Lay"},
    "P11": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "Hybrid-MedicalTextbooks + Expert"},
    "Q11": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "meqsum", "user_type": "layperson",
            "label": "Hybrid-HealthCareMagic + Lay"},
    "R11": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "bioasq_taskb", "user_type": "expert",
            "label": "Hybrid-HealthCareMagic + Expert"},
    "A22": {"retriever": "baseline", "corpus": "none", "queries": "medicationqa", "user_type": "layperson",
            "label": "Baseline + MedicationQA"},
    "B22": {"retriever": "baseline", "corpus": "none", "queries": "medqa", "user_type": "expert",
            "label": "Baseline + MedQA"},
    "C22": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "medicationqa", "user_type": "layperson",
            "label": "BM25-MedicalTextbooks + MedicationQA"},
    "D22": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "medqa", "user_type": "expert",
            "label": "BM25-MedicalTextbooks + MedQA"},
    "E22": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "medicationqa", "user_type": "layperson",
            "label": "BM25-HealthCareMagic + MedicationQA"},
    "F22": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "medqa", "user_type": "expert",
            "label": "BM25-HealthCareMagic + MedQA"},
    "G22": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "medicationqa", "user_type": "layperson",
            "label": "TFIDF-MedicalTextbooks + MedicationQA"},
    "H22": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "medqa", "user_type": "expert",
            "label": "TFIDF-MedicalTextbooks + MedQA"},
    "I22": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "medicationqa", "user_type": "layperson",
            "label": "TFIDF-HealthCareMagic + MedicationQA"},
    "J22": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "medqa", "user_type": "expert",
            "label": "TFIDF-HealthCareMagic + MedQA"},
    "K22": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "medicationqa", "user_type": "layperson",
            "label": "MedCPT-MedicalTextbooks + MedicationQA"},
    "L22": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "medqa", "user_type": "expert",
            "label": "MedCPT-MedicalTextbooks + MedQA"},
    "M22": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "medicationqa", "user_type": "layperson",
            "label": "MedCPT-HealthCareMagic + MedicationQA"},
    "N22": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "medqa", "user_type": "expert",
            "label": "MedCPT-HealthCareMagic + MedQA"},
    "O22": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "medicationqa", "user_type": "layperson",
            "label": "Hybrid-MedicalTextbooks + MedicationQA"},
    "P22": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "medqa", "user_type": "expert",
            "label": "Hybrid-MedicalTextbooks + MedQA"},
    "Q22": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "medicationqa", "user_type": "layperson",
            "label": "Hybrid-HealthCareMagic + MedicationQA"},
    "R22": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "medqa", "user_type": "expert",
            "label": "Hybrid-HealthCareMagic + MedQA"},
    "A1N": {"retriever": "baseline", "corpus": "none", "queries": "medredqa", "user_type": "layperson",
            "label": "Baseline + MedRedQA"},
    "B1N": {"retriever": "baseline", "corpus": "none", "queries": "medquad", "user_type": "expert",
            "label": "Baseline + MedQuAD"},
    "C1N": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "medredqa", "user_type": "layperson",
            "label": "BM25-MedicalTextbooks + MedRedQA"},
    "D1N": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "medquad", "user_type": "expert",
            "label": "BM25-MedicalTextbooks + MedQuAD"},
    "E1N": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "medredqa", "user_type": "layperson",
            "label": "BM25-HealthCareMagic + MedRedQA"},
    "F1N": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "medquad", "user_type": "expert",
            "label": "BM25-HealthCareMagic + MedQuAD"},
    "G1N": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "medredqa", "user_type": "layperson",
            "label": "TFIDF-MedicalTextbooks + MedRedQA"},
    "H1N": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "medquad", "user_type": "expert",
            "label": "TFIDF-MedicalTextbooks + MedQuAD"},
    "I1N": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "medredqa", "user_type": "layperson",
            "label": "TFIDF-HealthCareMagic + MedRedQA"},
    "J1N": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "medquad", "user_type": "expert",
            "label": "TFIDF-HealthCareMagic + MedQuAD"},
    "K1N": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "medredqa", "user_type": "layperson",
            "label": "MedCPT-MedicalTextbooks + MedRedQA"},
    "L1N": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "medquad", "user_type": "expert",
            "label": "MedCPT-MedicalTextbooks + MedQuAD"},
    "M1N": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "medredqa", "user_type": "layperson",
            "label": "MedCPT-HealthCareMagic + MedRedQA"},
    "N1N": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "medquad", "user_type": "expert",
            "label": "MedCPT-HealthCareMagic + MedQuAD"},
    "O1N": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "medredqa", "user_type": "layperson",
            "label": "Hybrid-MedicalTextbooks + MedRedQA"},
    "P1N": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "medquad", "user_type": "expert",
            "label": "Hybrid-MedicalTextbooks + MedQuAD"},
    "Q1N": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "medredqa", "user_type": "layperson",
            "label": "Hybrid-HealthCareMagic + MedRedQA"},
    "R1N": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "medquad", "user_type": "expert",
            "label": "Hybrid-HealthCareMagic + MedQuAD"},
    "A33": {"retriever": "baseline", "corpus": "none", "queries": "mashqa", "user_type": "layperson",
            "label": "Baseline + MASH-QA"},
    "B33": {"retriever": "baseline", "corpus": "none", "queries": "medmcqa", "user_type": "expert",
            "label": "Baseline + MedMCQA"},
    "C33": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "mashqa", "user_type": "layperson",
            "label": "BM25-MedicalTextbooks + MASH-QA"},
    "D33": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "medmcqa", "user_type": "expert",
            "label": "BM25-MedicalTextbooks + MedMCQA"},
    "E33": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "mashqa", "user_type": "layperson",
            "label": "BM25-HealthCareMagic + MASH-QA"},
    "F33": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "medmcqa", "user_type": "expert",
            "label": "BM25-HealthCareMagic + MedMCQA"},
    "G33": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "mashqa", "user_type": "layperson",
            "label": "TFIDF-MedicalTextbooks + MASH-QA"},
    "H33": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "medmcqa", "user_type": "expert",
            "label": "TFIDF-MedicalTextbooks + MedMCQA"},
    "I33": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "mashqa", "user_type": "layperson",
            "label": "TFIDF-HealthCareMagic + MASH-QA"},
    "J33": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "medmcqa", "user_type": "expert",
            "label": "TFIDF-HealthCareMagic + MedMCQA"},
    "K33": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "mashqa", "user_type": "layperson",
            "label": "MedCPT-MedicalTextbooks + MASH-QA"},
    "L33": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "medmcqa", "user_type": "expert",
            "label": "MedCPT-MedicalTextbooks + MedMCQA"},
    "M33": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "mashqa", "user_type": "layperson",
            "label": "MedCPT-HealthCareMagic + MASH-QA"},
    "N33": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "medmcqa", "user_type": "expert",
            "label": "MedCPT-HealthCareMagic + MedMCQA"},
    "O33": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "mashqa", "user_type": "layperson",
            "label": "Hybrid-MedicalTextbooks + MASH-QA"},
    "P33": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "medmcqa", "user_type": "expert",
            "label": "Hybrid-MedicalTextbooks + MedMCQA"},
    "Q33": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "mashqa", "user_type": "layperson",
            "label": "Hybrid-HealthCareMagic + MASH-QA"},
    "R33": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "medmcqa", "user_type": "expert",
            "label": "Hybrid-HealthCareMagic + MedMCQA"},
    "A44": {"retriever": "baseline", "corpus": "none", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "Baseline + ChatDoctor-iCliniq"},
    "B44": {"retriever": "baseline", "corpus": "none", "queries": "mmlu_medical", "user_type": "expert",
            "label": "Baseline + MMLU Medical"},
    "C44": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "BM25-MedicalTextbooks + ChatDoctor-iCliniq"},
    "D44": {"retriever": "bm25", "corpus": "medical_textbooks", "queries": "mmlu_medical", "user_type": "expert",
            "label": "BM25-MedicalTextbooks + MMLU Medical"},
    "E44": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "BM25-HealthCareMagic + ChatDoctor-iCliniq"},
    "F44": {"retriever": "bm25", "corpus": "healthcaremagic", "queries": "mmlu_medical", "user_type": "expert",
            "label": "BM25-HealthCareMagic + MMLU Medical"},
    "G44": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "TFIDF-MedicalTextbooks + ChatDoctor-iCliniq"},
    "H44": {"retriever": "tfidf", "corpus": "medical_textbooks", "queries": "mmlu_medical", "user_type": "expert",
            "label": "TFIDF-MedicalTextbooks + MMLU Medical"},
    "I44": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "TFIDF-HealthCareMagic + ChatDoctor-iCliniq"},
    "J44": {"retriever": "tfidf", "corpus": "healthcaremagic", "queries": "mmlu_medical", "user_type": "expert",
            "label": "TFIDF-HealthCareMagic + MMLU Medical"},
    "K44": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "MedCPT-MedicalTextbooks + ChatDoctor-iCliniq"},
    "L44": {"retriever": "medcpt", "corpus": "medical_textbooks", "queries": "mmlu_medical", "user_type": "expert",
            "label": "MedCPT-MedicalTextbooks + MMLU Medical"},
    "M44": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "MedCPT-HealthCareMagic + ChatDoctor-iCliniq"},
    "N44": {"retriever": "medcpt", "corpus": "healthcaremagic", "queries": "mmlu_medical", "user_type": "expert",
            "label": "MedCPT-HealthCareMagic + MMLU Medical"},
    "O44": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "Hybrid-MedicalTextbooks + ChatDoctor-iCliniq"},
    "P44": {"retriever": "hybrid", "corpus": "medical_textbooks", "queries": "mmlu_medical", "user_type": "expert",
            "label": "Hybrid-MedicalTextbooks + MMLU Medical"},
    "Q44": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "chatdoctor_icliniq", "user_type": "layperson",
            "label": "Hybrid-HealthCareMagic + ChatDoctor-iCliniq"},
    "R44": {"retriever": "hybrid", "corpus": "healthcaremagic", "queries": "mmlu_medical", "user_type": "expert",
            "label": "Hybrid-HealthCareMagic + MMLU Medical"},
}

EXTENDED_CONDITIONS.update(NEW_RETRIEVAL_CONDITIONS)

NEW_RETRIEVAL_CONDITION_IDS = [
    "A11", "B11", "C11", "D11", "E11", "F11",
    "G11", "H11", "I11", "J11", "K11", "L11",
    "M11", "N11", "O11", "P11", "Q11", "R11",
]

NEW_RETRIEVAL_CONDITION_IDS_22 = [
    "A22", "B22", "C22", "D22", "E22", "F22",
    "G22", "H22", "I22", "J22", "K22", "L22",
    "M22", "N22", "O22", "P22", "Q22", "R22",
]

NEW_RETRIEVAL_CONDITION_IDS_1N = [
    "A1N", "B1N", "C1N", "D1N", "E1N", "F1N",
    "G1N", "H1N", "I1N", "J1N", "K1N", "L1N",
    "M1N", "N1N", "O1N", "P1N", "Q1N", "R1N",
]

NEW_RETRIEVAL_CONDITION_IDS_33 = [
    "A33", "B33", "C33", "D33", "E33", "F33",
    "G33", "H33", "I33", "J33", "K33", "L33",
    "M33", "N33", "O33", "P33", "Q33", "R33",
]

NEW_RETRIEVAL_CONDITION_IDS_44 = [
    "A44", "B44", "C44", "D44", "E44", "F44",
    "G44", "H44", "I44", "J44", "K44", "L44",
    "M44", "N44", "O44", "P44", "Q44", "R44",
]

NEW_CONDITION_IDS = [
    "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R",
    "G1", "H1", "I1", "J1", "K1", "L1", "M1", "N1", "O1", "P1", "Q1", "R1",
    "G2", "H2", "I2", "J2", "K2", "L2", "M2", "N2", "O2", "P2", "Q2", "R2",
    "G3", "H3", "I3", "J3", "K3", "L3", "M3", "N3", "O3", "P3", "Q3", "R3",
    "G4", "H4", "I4", "J4", "K4", "L4", "M4", "N4", "O4", "P4", "Q4", "R4",
] + NEW_RETRIEVAL_CONDITION_IDS + NEW_RETRIEVAL_CONDITION_IDS_22 + NEW_RETRIEVAL_CONDITION_IDS_1N + NEW_RETRIEVAL_CONDITION_IDS_33 + NEW_RETRIEVAL_CONDITION_IDS_44
